food/urls.py
from django.contrib import admin
from django.urls import path, include
from food1 import views
from food1.signup import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('food/', include('food1.urls', namespace='food')),
    path('api/v1/pizza/', include('food1.urls')),
    path('signup/', v.signup, name="signup"),
    path('', include("django.contrib.auth.urls")),
]

food1/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views
from .views import PizzaViewSet

app_name = 'fastfood'
router = routers.SimpleRouter()
router.register(r'', PizzaViewSet)

urlpatterns = [
    path('pizza', views.pizza, name='pizza'),
    path('burgers', views.burgers, name='burgers'),
    path('order', views.order, name='order'),
    path('success', views.success, name='success'),
    path('login', views.logIn, name='login'),
    path('logout', views.logOut, name='logout'),
    path('', include(router.urls,)),
]

food1/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now

# Create your models here.
class Pizza(models.Model):
    name   = models.CharField(max_length=120)
    priceM = models.IntegerField(blank=True, null=True)
    priceL = models.IntegerField(blank=True, null=True)
    pImage = models.URLField()


class Burger(models.Model):
    name   = models.CharField(max_length=120)
    priceM = models.IntegerField(blank=True, null=True)
    priceL = models.IntegerField(blank=True, null=True)
    bImage = models.URLField()

class Order(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    number   = models.CharField(max_length=60)
    bill     = models.IntegerField(blank=True, null=True)
    date     = models.DateTimeField(default=now, editable=False)
    note     = models.TextField(blank=True, null=True)

class Item(models.Model):
    order  = models.ForeignKey(Order, on_delete=models.CASCADE)
    name   = models.CharField(max_length=120)
    price  = models.IntegerField(blank=True, null=True)
    size   = models.CharField(max_length=60)

food1/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

food1/signup/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

food1/signup/views.py
from django.shortcuts import render, redirect
from .forms import SignupForm
from django.contrib.auth import authenticate

# Create your views here.
def signup(response):
    if response.method == "POST":
        form = SignupForm(response.POST)
        if form.is_valid():
            form.save()

        return redirect("index")    
    else:
        form = SignupForm()


    form = SignupForm()
    return render(response, "signup/signup.html", {"form": form})

food1/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Pizza, Burger, Order, Item
from rest_framework import serializers, viewsets
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import SignupForm
import random
import json
def randomOrderNumber(length):
    sample = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890'
    number0 = ''.join((random.choice(sample) for i in range(length)))
    return number0
# Create your views here.

def index(request):
    request.session.set_expiry(0)
    ctx = {'active_link': 'index'}
    return render(request, 'food1/index.html', ctx)

def pizza(request):
    request.session.set_expiry(0)
    pizzas = Pizza.objects.all()
    ctx = {'pizzas': pizzas, 'active_link': 'pizza'}

    return render(request, 'food1/pizza.html', ctx)


def burgers(request):
    request.session.set_expiry(0)
    burgers = Burger.objects.all()
    ctx = {'burgers': burgers, 'active_link': 'burger'}

    return render(request, 'food1/burgers.html', ctx)

@csrf_exempt
def order(request):
    request.session.set_expiry(0)
    if request.is_ajax():
        request.session['note'] = request.POST.get('note')
        request.session['order'] = request.POST.get('orders')
        orders = json.loads(request.session['order'])
        request.session['bill'] = request.POST.get('bill')
        randomNum = randomOrderNumber(6)

        while Order.objects.filter(number=randomNum).count() > 0:
            randomNum = randomOrderNumber(6)

        if request.user.is_authenticated:
            order = Order(customer=request.user, 
                            number=randomNum, 
                            bill=float(request.session['bill']), 
                            note=request.session['note'])
            order.save()
            for article in orders:
                item = Item(
                    order = order,
                    name  = article[0],
                    price = float(article[2]),
                    size  = article[1]
                )
                item.save()
    ctx = {'active_link': 'order'}
    return render(request, 'food1/cart.html', ctx)

def success(request):
    order = request.session['order']
    ctx = {'order' : order}
    return render(request, 'food1/success.html', ctx)

def logIn(request):
    if request.POST:
        username = request.POST.get('username')
        pwd = request.POST.get('password')
        account = authenticate(request, username=username, password=pwd)
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            messages.info(request, 'username and/or password are incorrect')
    ctx = {'active_link': 'login'}
    return render(request, "food1/login.html", ctx)

def logOut(request):
    logout(request)
    return redirect("index")


# Rest api pizza
class PizzaSerializer(serializers.ModelSerializer):
    class Meta:
        model = Pizza
        fields = ('id', 'name', 'priceM', 'priceL', 'pImage',)

class PizzaViewSet(viewsets.ModelViewSet):
    queryset = Pizza.objects.all()
    serializer_class = PizzaSerializer

food1/templates/food1/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %} {% endblock %}</title>
        <link rel="icon" type="image/png" href="https://img.icons8.com/cotton/40/000000/beefburger.png">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'food1/css/style.css' %}">
        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    </head>
    <body>
            <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
                    <!-- Brand/logo -->
                    <a class="navbar-brand" href="{% url 'index' %}">
                        <img src="https://img.icons8.com/cotton/40/000000/beefburger.png" class="logo"/>
                    </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mynav" aria-controls="mynav">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="mynav">
                    <!-- Links -->
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link {% if active_link == 'index' %}active{% endif %}" href="{% url 'index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if active_link == 'pizza' %}active{% endif %}" href="{% url 'food:pizza' %}">Pizza</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if active_link == 'burger' %}active{% endif %}" href="{% url 'food:burgers' %}">Burger</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item mt-2">
                            <a href="" class="nav-link"><img class="pr-1" src="https://img.icons8.com/office/30/000000/shopping-cart.png"/><span id="cart"></span></a>
                        </li>
                        <li class="nav-item">
                            <a href="" class="nav-link"><img class="ml-1 rounded-circle" src="https://img.icons8.com/doodle/32/000000/test-account.png"/><br>Login</a>
                        </li>
                    </ul>
                </div>
            </nav>
            
            <div>
                {% block content %} {% endblock %}
            </div>
        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <!-- Popper JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script src="{% static 'food1/js/main.js' %}"></script>
    </body>
</html>

food1/templates/food1/login.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Login{% endblock %}</title>
    <link rel="icon" type="image/png" href="https://res.cloudinary.com/dzosnc60i/image/upload/v1607690810/fastfood/logo1_beurei.png">
    <meta name="description" content="Resto">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    {% load crispy_forms_tags %}
    <!-- External CSS -->
    <link rel="stylesheet" href="{% static 'food1/vendor/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'food1/vendor/select2/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'food1/vendor/owlcarousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="https://cdn.rawgit.com/noelboss/featherlight/1.7.13/release/featherlight.min.css">
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.1/css/brands.css">

    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat&display=swap">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700|Josefin+Sans:300,400,700">
    <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
        integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
        <script src="https://use.fontawesome.com/5b67370c4c.js"></script>


    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'food1/css/style.css' %}">



</head>

<body id="Index" data-spy="scroll" data-target="#navbar" class="static-layout">
    <div id="side-nav" class="sidenav">
        <a href="javascript:void(0)" id="side-nav-close">&times;</a>

        <div class="sidenav-content">
            <p>
                Kuncen WB1, Wirobrajan 10010, DIY
            </p>
            <p>
                <span class="fs-16 primary-color">(+216) 52 450 636</span>
            </p>
            <p>info@yourdomain.com</p>
        </div>
    </div>
    <div id="side-search" class="sidenav">
        <a href="javascript:void(0)" id="side-search-close">&times;</a>
        <div class="sidenav-content">
            <form action="">

                <div class="input-group md-form form-sm form-2 pl-0">
                    <input class="form-control my-0 py-1 red-border" type="text" placeholder="Search"
                        aria-label="Search">
                    <div class="input-group-append">
                        <button class="input-group-text red lighten-3" id="basic-text1">
                            <i class="fas fa-search text-grey" aria-hidden="true"></i>
                        </button>
                    </div>
                </div>

            </form>
        </div>


    </div>
    <div id="canvas-overlay"></div>
    <div class="boxed-page">
        <nav id="navbar-header" class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand navbar-brand-center d-flex align-items-center p-0 only-mobile" href="{% url 'index' %}">
                    <img src="https://res.cloudinary.com/dzosnc60i/image/upload/v1607690810/fastfood/logo1_beurei.png" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="lnr lnr-menu"></span>
                </button>

                <a class="navbar-brand justify-content-start d-flex align-items-center p-0 only-desktop" href="{% url 'index' %}">
                    <img src="https://res.cloudinary.com/dzosnc60i/image/upload/v1607690810/fastfood/logo1_beurei.png" class="img-fluid footer-logo mb-3" alt="">
                </a>
                
                <div class="collapse navbar-collapse justify-content-start" id="navbarSupportedContent">
                    <ul class="navbar-nav d-flex justify-content-start">
                        <li class="nav-item only-desktop">
                            <a class="nav-link" id="side-nav-open" href="#"></a>
                        </li>
                        <div class="d-flex flex-lg-row flex-column">
                            <li class="nav-item active mr-4">
                                <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item mr-4">
                                <a class="nav-link" href="#about">About</a>
                            </li>

                        </div>
                    </ul>

                    
                    <ul class="navbar-nav d-flex justify-content-end">
                        <div class="d-flex flex-lg-row flex-column">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle mr-4" href="#" id="navbarDropdown" role="button"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Menu
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{% url 'food:pizza' %}">Breakfast</a>
                                    <a class="dropdown-item" href="{% url 'food:burgers' %}">Lunch/Dinner</a>
                                </div>
                            </li>
                            

                            {% if user.is_authenticated %}
                            <li class="nav-item mr-4">
                                <a class="nav-link" href="{% url 'food:logout' %}">Logout</a>
                            </li>
                            {% else %}
                            <li class="nav-item mr-4">
                                <a class="nav-link" href="{% url 'food:login' %}">Login</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
                            </li>
                            {% endif %}
                            
                            <li class="nav-item ml-5">
                            <style>
                                .btn-outline-danger:hover {
                                    color:white !important;
                                }
                            </style>
                                <a href="{% url 'food:order' %}" class="btn btn-outline-danger">
                                    <i class="fa fa-shopping-cart" style="opacity:1"></i><span class="badge badge-sm-light" id="cart"></span>
                                </a>
                            </li>
                        </div>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container-fluid p-5 ">
            <div class="row">
                <div class="m-auto">
                    <h3 class="text-center p-4">Login</h3>
                    <form method="POST" action="{% url 'food:login' %}" class="form-group">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="text" name="username" placeholder="Username">
                        </div>
                        <div class="form-group">
                            <input type="text" name="password" placeholder="***********">
                        </div>
                        <button type="submit" class="btn btn-success">Login</button>
                        {% if messages %}
                            <ul class="pt-2 text-center">
                                {% for msg in messages %}
                                <li style="color:red">{{ msg }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>

        <!-- End of Reservation Section -->
        <footer class="mastfoot pb-5 bg-white section-padding pb-0">
            <div class="inner container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="footer-widget pr-lg-5 pr-0">
                            <img src="https://res.cloudinary.com/dzosnc60i/image/upload/v1607690810/fastfood/logo1_beurei.png" class="img-fluid footer-logo mb-3" class="img-fluid footer-logo mb-3" alt="">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et obcaecati quisquam id sit
                                omnis explicabo voluptate aut placeat, soluta, nisi ea magni facere, itaque incidunt
                                modi? Magni, et voluptatum dolorem.</p>
                            <nav class="nav nav-mastfoot justify-content-start">
                                <a class="nav-link" href="#">
                                    <i class="fab fa-facebook-f"></i>
                                </a>
                                <a class="nav-link" href="#">
                                    <i class="fab fa-twitter"></i>
                                </a>
                                <a class="nav-link" href="#">
                                    <i class="fab fa-instagram"></i>
                                </a>
                            </nav>
                        </div>

                    </div>
                    <div class="col-lg-4">
                        <div class="footer-widget px-lg-5 px-0">
                            <h4>Open Hours</h4>
                            <ul class="list-unstyled open-hours">
                                <li class="d-flex justify-content-between"><span>Monday</span><span>9:00 - 24:00</span>
                                </li>
                                <li class="d-flex justify-content-between"><span>Tuesday</span><span>9:00 - 24:00</span>
                                </li>
                                <li class="d-flex justify-content-between"><span>Wednesday</span><span>9:00 -
                                        24:00</span></li>
                                <li class="d-flex justify-content-between"><span>Thursday</span><span>9:00 -
                                        24:00</span></li>
                                <li class="d-flex justify-content-between"><span>Friday</span><span>9:00 - 02:00</span>
                                </li>
                                <li class="d-flex justify-content-between"><span>Saturday</span><span>9:00 -
                                        02:00</span></li>
                                <li class="d-flex justify-content-between"><span>Sunday</span><span> Closed</span></li>
                            </ul>
                        </div>

                    </div>

                    <div class="col-lg-4">
                        <div class="footer-widget pl-lg-5 pl-0">
                            <h4>Newsletter</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <form id="newsletter">
                                <div class="form-group">
                                    <input type="email" class="form-control" id="emailNewsletter"
                                        aria-describedby="emailNewsletter" placeholder="Enter email">
                                </div>
                                <button type="submit" class="btn btn-primary w-100">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </footer>



            <!-- External JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script src="{% static 'food1/vendor/bootstrap/popper.min.js' %}"></script>
    <script src="{% static 'food1/vendor/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'food1/vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'food1/vendor/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="https://cdn.rawgit.com/noelboss/featherlight/1.7.13/release/featherlight.min.js"></script>
    <script src="{% static 'food1/vendor/stellar/jquery.stellar.js' %}" type="text/javascript" charset="utf-8"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Main JS -->
    <script src="{% static 'food1/js/app.min.js' %} "></script>
</body>

</html
            